_core:
  default_config_hash: jdY7AU0tU-QsjmiOw3W8vwpYMb-By--_MSFgbqKUTYM
definitions:
  system__admin:
    menu_name: admin
    parent: ''
    weight: 9
    expanded: false
    enabled: true
  system__admin_structure:
    menu_name: admin
    parent: system.admin
    weight: -8
    expanded: false
    enabled: true
